name: JIRA Guru
favicon: null
layout_spectrum: 0.1849320917390287
typography_spectrum: 0.16248108493164182
title: JIRA Guru
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9679468595422804
  lightness: 0.2363768604118377
  saturation: 0.530187692726031
  rhythmicContrast: 0.07949276873841882
purpose: []
